spring:
  application:
    name: Bento-backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: Bento_Data
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

